### ISSUE TITLE
Any way to see progress of the GPT answer?

### ISSUE THREAD

**Issue by jnpatrick99** [Kav-K/GPT3Discord#135]
**Is your feature request related to a problem? Please describe.**
Original ChatGPT "types" the answer so we can see the progress of it, it's very convenient when the answer is huge - you don't have to wait.

**Describe the solution you'd like**
Same with GPT3Discord bot! See the answer evolving

**Describe alternatives you've considered**
No

**Comment by Kav-K** [comment]
Hmm, this isn't possible at all due to the discord rate limits on message editing. Do you have any other alternatives? Maybe like a loading bar or something?

**Comment by jnpatrick99** [comment]
I see! Thanks for the answer. I know nothing about discord bot programming so pardon me my incompetence. I asked ChatGPT what's the best way to do it, here's the answer haha:

``
The Discord API has a method called typing which allows the bot to simulate typing in a channel. By calling this method repeatedly and updating the message with new lines, you can simulate a message being typed line by line. Here is an example of how this could be implemented in JavaScript:
``

Totally not sure if it's correct.

So the main idea is to have huge multiline answers appear line by one (or maybe in chunks?). Thanks again!

**Comment by Kav-K** [comment]
ChatGPT is unreliable for answers about OpenAI services (ironically) since they're so new. There is a feature called "typing" but it is just the text that says "Bot is typing..." at the bottom of the channel screen, it's not used to post answers piece by piece.

The issue with sending messages in an interval to the channel over time like in the code snippet you sent is is, if somebody else types it will break the flow and it will not look cohesive and look weird, and also if multiple people are asking for a long answer, the bot will get rate limited because it's always sending small updates to all those users prompts

**Comment by jnpatrick99** [comment]
Yeah makes sense! Well, OK ¯\_(ツ)_/¯ Thanks! That's unfortunate.

**Comment by Kav-K** [comment]
Let me know if you think of any other ideas that could be implemented, I cant think of any right now unfortunately :(
