### ISSUE TITLE
[Question] when running - None of PyTorch, TensorFlow >= 2.0, or Flax have been found. - Bot wont run

### ISSUE THREAD

**Issue by jphccfc** [Kav-K/GPT3Discord#26]
I think this may actually be a config issue on my DO server - I had to restart my droplet and update the debug channel in the .env to debug to a seperate channel and since then I cant get the bot to run - I get the following error message when i run screen python3.9 main.py

"None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used."

I had it working fine last night!

**Comment by jphccfc** [comment]
Ive tried to run it direct in putty and now get the following error -   File "/root/GPT3Discord/main.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

I have done a full rerun from the start of the installation instructions

**Comment by Kav-K** [comment]
Hi there,

"None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used."

This is not an error. This happens because we are only using the GPT2Tokenizer and no models. The bot will work perfectly if you see this and no other errors. You reinstalled a working version, it seems like after you attempted to reinstall, pycord was not installed correctly

**Comment by jphccfc** [comment]
Thanks Kav - I did try and reinstall py-cord and get the following response - 

Requirement already satisfied: py-cord in /usr/local/lib/python3.9/dist-packages (2.3.2)
Requirement already satisfied: typing-extensions<5,>=4 in /usr/local/lib/python3.9/dist-packages (from py-cord) (4.4.0)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in /usr/local/lib/python3.9/dist-packages (from py-cord) (3.8.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (1.3.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (2.1.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (21.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp<3.9.0,>=3.6.0->py-cord) (6.0.4)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.9.0,>=3.6.0->py-cord) (3.3)

**Comment by jphccfc** [comment]
I deleted the droplet and reinstalled and eventually got it working. thanks for your help.

**Comment by falkoro** [comment]
I have the same issue, tried to reinstall but not working yet. I also get the same error, the bot stays offline.

**Comment by falkoro** [comment]
When I try to run it non-screen I get this error: azureuser@chatgpt:~/GPT3Discord$ python3.9 gpt3discord.py
The environment file is located at /home/azureuser/GPT3Discord/.env
/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/home/azureuser/.local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
Process ID file already exists
azureuser@chatgpt:~/GPT3Discord$
