### ISSUE TITLE
COMMANDS NOT SHOWING [BUG] 

### ISSUE THREAD

**Issue by motikolorado** [Kav-K/GPT3Discord#36]
I just hosted it and only the delete-channel command and usage is showing...
<img width="625" alt="Screenshot 2022-12-31 at 6 53 55 AM" src="https://user-images.githubusercontent.com/83591079/210137496-be52486a-0b10-48cd-9ac1-ecdcbb1765cd.png">

**Comment by motikolorado** [comment]
In the env file, there's a variable for allowed_roles="admin,gpt"

I don't have any roles with these names in my server. Do I create these roles or just past a role iD there.

Another question, if I want everyone to be allowed to use the bot, should I just leave the role empty?


I also don't know if the allowed role is for members or admin commands.

What is the allowed role for?

**Comment by Kav-K** [comment]
If you want everyone to use the bot, you need to give everyone the role, I will make it such that if it's empty it'll default to everyone.

The ALLOWED_ROLES is for ALL commands. You can create the role and paste the role *name* there

If the commands aren't showing up on your server, you may have set the ALLOWED_GUILDS incorrect, have you double checked that ALLOWED_GUILDS is your guild ID?

**Comment by Kav-K** [comment]
Hey I'm going to close this for now, as I'm pretty sure commands are registering correctly, please make sure you have your ALLOWED_GUILDS set correctly again. I'll be adding a feature where you can allow all users to use it instead of restricting by ALLOWED_ROLES, so be on the lookout for that :) 

Feel free to reopen this if you have more issues, but please try a fresh install with the latest release
