### ISSUE TITLE
Unclosed connector while running main.py

### ISSUE THREAD

**Issue by yigitkonur** [Kav-K/GPT3Discord#7]
I've followed exactly same steps of README, running on Ubuntu 19 and Python 3.10.

Here is the output:

```
root@discord-bots:~/GPT3Discord# python3 main.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/root/GPT3Discord/main.py:23: DeprecationWarning: There is no current event loop
  asyncio.ensure_future(Message.process_message_queue(message_queue, 1.5, 5))
/root/GPT3Discord/main.py:24: DeprecationWarning: There is no current event loop
  asyncio.ensure_future(Deletion.process_deletion_queue(deletion_queue, 1, 1))
Wrote PID to file the file bot.pid
/root/GPT3Discord/main.py:78: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
Conversation starter text loaded from file.
The debug channel and guild IDs are 793253342490918912 and 1054226060415356938
Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Removing PID file
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa0ee96d150>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fa0ee937040>, 166.232241252)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fa0ee96d120>
```

**Comment by Kav-K** [comment]
Hi, I am looking into it now. In the meanwhile, can you please try with python 3.9?

**Comment by yigitkonur** [comment]
Btw, great product and excited me a lot!

**Comment by Kav-K** [comment]
> Btw, great product and excited me a lot! Unfortunately, I've tried with 3.9 but the same response returns.

Thank you! 

As for your issue, I've tried to reproduce it locally, but I am able to set it up just fine using both python 3.9 and python 3.10. None of the issues seen in the terminal about asyncio are breaking issues and they'll still work. However, something that I noticed in your error output was that it said
`Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.`

Can you go ahead and try doing that? I think the bot might not be starting up because the intents are not enabled. Try to enable all the intents, such as the message content intent, presence intent, etc. 

Also, I've slightly updated the branch to have a bit more verbose debugging, so if it still doesnt work, paste your error message here again :)

**Comment by yigitkonur** [comment]
Oh, presence intent is just fixed the problem. Works like a charm! Many thanks.
